spring.application.name=bff-agendador-tarefas
server.port=8083

usuario.url=http://localhost:8080/usuario
agendador-tarefas.url=http://localhost:8081/tarefas
notificacao.url=http://localhost:8081/email

